[build]
  publish = "dist"
  command = "npm install && npm run build"
 
[[redirects]]
  from = "http://dgdocs.ole.dev/*"
  to = "http://dg-docs.ole.dev/:splat"
  status = 301
  
[[redirects]]
  from = "https://dgdocs.ole.dev/*"
  to = "https://dg-docs.ole.dev/:splat"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404


